# Dependencies
markdown:         rdiscount
highlighter:      pygments
 
# Permalinks
permalink:        /blog/:categories/:title.html
 
# Server
destination:      _site
host:             localhost
port:             9001
url:       		  http://localhost:9001
mobileurl:        http://m.nicowatine.me
awsurl:		  	  http://d19ocv12oznz5.cloudfront.net
sncurl: 		  http://studioncreations.com/nicowatine
baseurl:          /
encoding:         UTF-8
